### ISSUE TITLE
xilinx-zynq-a9 machine 

### ISSUE THREAD

**Issue by radwrob** [Xilinx/systemctlm-cosim-demo#1]
Hello Xilinx,

Now I use the Xilinx's QEMU platform (xilinx-v2016.3 tag) instead of PetaLinux. When I start this project on machine **arm-generic-fdt-plnx** everything is working properly. While I changes to the machine **xilinx-zynq-a9**, platform qemu does not stop and does not display the message:

> QEMU waiting for connection on: Disconnected: unix: ./ qemu-tmp / qemu-rport-_cosim @ 0 server

Linux kernel is loaded instead of this:

>   Uncompressing Linux ... done, booting the kernel.

Any ideas why this happens?

Thanks,
Radek

**Comment by edgarigl** [comment]
Hi Radek,

Yes, in order to co-simulate, you need to instantiate the remote-port nodes. These nodes are described in a cosim device-tree that arm-generic-fdt-plnx consumes. When you run the xilinx-zynq-a9 machine, because that machine does not support co-simulation, the remote-port nodes are not created and a normal boot begins.

Hope that helps,

Best regards,
Edgar

**Comment by radwrob** [comment]
Hi Edgar,

Thank you for your prompt reply.

Regards,
Radek
